application: virtualjoker
version: 0
runtime: python
api_version: 1

handlers:
- url: /(.*\.(ico))
  static_files: static/ico/\1
  upload: static/ico/(.*\.(ico))

- url: /(.*\.(css))
  static_files: static/css/\1
  upload: static/css/(.*\.(css))

- url: /(.*\.(js))
  static_files: static/js/\1
  upload: static/js/(.*\.(js))

- url: /(.*\.(gif|png|jpg))
  static_files: static/image/\1
  upload: static/image/(.*\.(gif|png|jpg))


- url: /cron_jobs
  script: cron_jobs_handler.py
  login: admin

- url: /server
  script: server_handler.py
  login: admin

- url: /feeder
  script: feeder_handler.py

- url: /action
  script: action_handler.py

- url: /.*
  script: main_handler.py
